apiVersion: v1
kind: Pod
metadata:
  name: hono-nodejs
  namespace: hono-nodejs
spec:
  containers:
    - name: app
      image: docker.io/library/hono-nodejs:latest
      envFrom:
        - configMapRef:
            name: hono-nodejs-configmap
