info:
  version: 0.0.0
  title: hono-nodejs
  description: Hono on NodeJS
openapi: 3.1.0
components:
  schemas: {}
  parameters: {}
paths:
  /todos:
    post:
      summary: todoの新規作成
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  minLength: 1
              required:
                - title
      responses:
        '200':
          description: todoの新規作成成功
          content:
            application/json:
              schema:
                type: object
                properties: {}
    get:
      summary: todoの一覧取得
      parameters:
        - in: query
          name: status
          schema:
            type: string
            enum:
              - progress
              - pending
              - done
            default: progress
          required: true
      responses:
        '200':
          description: todoの一覧取得成功
          content:
            application/json:
              schema:
                type: object
                properties: {}
  '/todos/{id}':
    delete:
      summary: todoの削除
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
      responses:
        '200':
          description: todoの削除成功
        '404':
          description: 対象のtodoが存在しない
    get:
      summary: todoの取得
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
      responses:
        '200':
          description: todoの取得成功
          content:
            application/json:
              schema:
                type: object
                properties: {}
        '404':
          description: 対象のtodoが存在しない
    patch:
      summary: todoの更新
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  minLength: 1
                status:
                  type: string
                  enum:
                    - progress
                    - pending
                    - done
      responses:
        '200':
          description: todoの更新成功
          content:
            application/json:
              schema:
                type: object
                properties: {}
  /todos/search:
    get:
      summary: todoの検索
      parameters:
        - in: query
          name: title
          schema:
            type: string
            minLength: 1
          required: false
        - in: query
          name: status
          schema:
            type: string
            enum:
              - progress
              - pending
              - done
          required: false
      responses:
        '200':
          description: todoの検索成功
          content:
            application/json:
              schema:
                type: object
                properties: {}
