openapi: 3.1.0
info:
  version: 0.0.0
  title: hono-on-node
  description: Hono on NodeJS
paths:
  /todos:
    get:
      description: Todoの一覧取得
      parameters:
        - in: query
          name: status
          schema:
            type: string
            enum:
              - progress
              - pending
              - done
            default: progress
      responses:
        "200":
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: number
                    title:
                      type: string
                    status:
                      type: string
                      enum: &a1
                        - progress
                        - pending
                        - done
                    created_at:
                      type: string
                    updated_at:
                      type:
                        - string
                        - "null"
                    deleted_at:
                      type:
                        - string
                        - "null"
                  required:
                    - id
                    - title
                    - status
                    - created_at
                    - updated_at
                    - deleted_at
        "400":
          content:
            application/json:
              schema: {}
        "500":
          content:
            application/json:
              schema: {}
    post:
      description: Todoの新規作成
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  minLength: 1
              required:
                - title
      responses:
        "200":
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: number
                  title:
                    type: string
                  status:
                    type: string
                    enum: *a1
                  created_at:
                    type: string
                  updated_at:
                    type:
                      - string
                      - "null"
                  deleted_at:
                    type:
                      - string
                      - "null"
                required:
                  - id
                  - title
                  - status
                  - created_at
                  - updated_at
                  - deleted_at
        "400":
          content:
            application/json:
              schema: {}
        "500":
          content:
            application/json:
              schema: {}
  /todos/:id:
    get:
      description: Todoの取得
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: number
                  title:
                    type: string
                  status:
                    type: string
                    enum: *a1
                  created_at:
                    type: string
                  updated_at:
                    type:
                      - string
                      - "null"
                  deleted_at:
                    type:
                      - string
                      - "null"
                required:
                  - id
                  - title
                  - status
                  - created_at
                  - updated_at
                  - deleted_at
        "400":
          content:
            application/json:
              schema: {}
        "404":
          content:
            application/json:
              schema: {}
        "500":
          content:
            application/json:
              schema: {}
    patch:
      description: Todoの更新
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  minLength: 1
                status:
                  type: string
                  enum:
                    - progress
                    - pending
                    - done
      responses:
        "200":
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: number
                  title:
                    type: string
                  status:
                    type: string
                    enum: *a1
                  created_at:
                    type: string
                  updated_at:
                    type:
                      - string
                      - "null"
                  deleted_at:
                    type:
                      - string
                      - "null"
                required:
                  - id
                  - title
                  - status
                  - created_at
                  - updated_at
                  - deleted_at
        "400":
          content:
            application/json:
              schema: {}
        "404":
          content:
            application/json:
              schema: {}
        "500":
          content:
            application/json:
              schema: {}
    delete:
      description: Todoの削除
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                type: "null"
        "400":
          content:
            application/json:
              schema: {}
        "404":
          content:
            application/json:
              schema: {}
        "500":
          content:
            application/json:
              schema: {}
  /todos/search:
    get:
      description: Todoの検索
      parameters:
        - in: query
          name: title
          schema:
            type: string
            minLength: 1
        - in: query
          name: status
          schema:
            type: string
            enum:
              - progress
              - pending
              - done
      responses:
        "200":
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: number
                    title:
                      type: string
                    status:
                      type: string
                      enum: *a1
                    created_at:
                      type: string
                    updated_at:
                      type:
                        - string
                        - "null"
                    deleted_at:
                      type:
                        - string
                        - "null"
                  required:
                    - id
                    - title
                    - status
                    - created_at
                    - updated_at
                    - deleted_at
        "400":
          content:
            application/json:
              schema: {}
        "500":
          content:
            application/json:
              schema: {}
