openapi: 3.1.0
info:
  version: 0.0.0
  title: hono-nodejs
  description: Hono on NodeJS
components:
  schemas: {}
  parameters: {}
paths:
  /todos:
    get:
      summary: todoの一覧取得
      parameters:
        - schema:
            type: string
            enum:
              - progress
              - pending
              - done
            default: progress
          required: true
          name: status
          in: query
      responses:
        "200":
          description: todoの一覧取得成功
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: number
                    title:
                      type: string
                    status:
                      type: string
                      enum: &a1
                        - progress
                        - pending
                        - done
                    created_at:
                      type: string
                    updated_at:
                      type:
                        - string
                        - "null"
                    deleted_at:
                      type:
                        - string
                        - "null"
                  required:
                    - id
                    - title
                    - status
                    - created_at
                    - updated_at
                    - deleted_at
                  additionalProperties: false
    post:
      summary: todoの新規作成
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  minLength: 1
              required:
                - title
              additionalProperties: false
      responses:
        "200":
          description: todoの新規作成成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: number
                  title:
                    type: string
                  status:
                    type: string
                    enum: *a1
                  created_at:
                    type: string
                  updated_at:
                    type:
                      - string
                      - "null"
                  deleted_at:
                    type:
                      - string
                      - "null"
                required:
                  - id
                  - title
                  - status
                  - created_at
                  - updated_at
                  - deleted_at
                additionalProperties: false
  /todos/search:
    get:
      summary: todoの検索
      parameters:
        - schema:
            type: string
            minLength: 1
          required: false
          name: title
          in: query
        - schema:
            type: string
            enum:
              - progress
              - pending
              - done
          required: false
          name: status
          in: query
      responses:
        "200":
          description: todoの検索成功
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: number
                    title:
                      type: string
                    status:
                      type: string
                      enum: *a1
                    created_at:
                      type: string
                    updated_at:
                      type:
                        - string
                        - "null"
                    deleted_at:
                      type:
                        - string
                        - "null"
                  required:
                    - id
                    - title
                    - status
                    - created_at
                    - updated_at
                    - deleted_at
                  additionalProperties: false
  "/todos/{id}":
    patch:
      summary: todoの更新
      parameters:
        - schema:
            type: string
          required: true
          name: id
          in: path
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  minLength: 1
                status:
                  type: string
                  enum:
                    - progress
                    - pending
                    - done
              additionalProperties: false
      responses:
        "200":
          description: todoの更新成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: number
                  title:
                    type: string
                  status:
                    type: string
                    enum: *a1
                  created_at:
                    type: string
                  updated_at:
                    type:
                      - string
                      - "null"
                  deleted_at:
                    type:
                      - string
                      - "null"
                required:
                  - id
                  - title
                  - status
                  - created_at
                  - updated_at
                  - deleted_at
                additionalProperties: false
    delete:
      summary: todoの削除
      parameters:
        - schema:
            type: string
          required: true
          name: id
          in: path
      responses:
        "200":
          description: todoの削除成功
        "404":
          description: 対象のtodoが存在しない
    get:
      summary: todoの取得
      parameters:
        - schema:
            type: string
          required: true
          name: id
          in: path
      responses:
        "200":
          description: todoの取得成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: number
                  title:
                    type: string
                  status:
                    type: string
                    enum: *a1
                  created_at:
                    type: string
                  updated_at:
                    type:
                      - string
                      - "null"
                  deleted_at:
                    type:
                      - string
                      - "null"
                required:
                  - id
                  - title
                  - status
                  - created_at
                  - updated_at
                  - deleted_at
                additionalProperties: false
        "404":
          description: 対象のtodoが存在しない
webhooks: {}
